# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Install system dependencies if needed
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy the entire project to /app
COPY . /app

# Upgrade pip and install the package in editable mode
RUN pip install --upgrade pip
RUN pip install -e .

# Expose any necessary ports if applicable (none required for stdio based MCP)

# Default command to run the MCP server using python module entrypoint
CMD ["python", "-m", "./src/pdf2md"]
